[package]
name = "html_diff"
version = "0.1.0"
authors = ["becker <github@deathbyescalator.com>"]
edition = "2018"

[dependencies]
regex = "1"
difference = "2.0"
[dev-dependencies]
pretty_assertions = "*"
